"""empty message

Revision ID: 2ea6cea567c1
Revises: fe81deb43884
Create Date: 2025-05-27 11:19:48.884231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea6cea567c1'
down_revision = 'fe81deb43884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('nota', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividades', 'nota')
    # ### end Alembic commands ###
